pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'javac src/HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                sh 'java -cp src HelloWorld'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
